SID = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' #This is available at your Twilio account.
AUTH_TOKEN = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxx' #This is available at your Twilio account.
FROM_NUMBER = +12xxxxxxxx #This is the unique number generated by your Twilio.
TO_NUMBER = +91xxxxxxxxxx  #This is the phone no. to which the message need to be sent.
API_KEY = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxx' #This is the API key generated by your bolt device.
DEVICE_ID = 'BOLT13xxxxxx' #This is the unique Bolt device ID.
